### ISSUE TITLE
Running the Project

### ISSUE THREAD

**Issue by vikingwarior** [AnneLivia/RSPGameRMI#1]
Hi, I am facing trouble in running this prohect. Can you please tell how can I run this project step-by-step. Thanks

Here is the error message I'm facing when I try to run the jar
![image](https://user-images.githubusercontent.com/73878892/233776438-1741038a-0a66-47de-bbf1-2b1387907f60.png)

**Comment by AnneLivia** [comment]
Hi, in order to run this project, you need to execute first the file serveRMI.java, and then ClientGameSRP.java.

https://user-images.githubusercontent.com/31932673/233793034-6dfd79ae-185b-462f-8d2a-f702c8685b91.mp4

**Comment by vikingwarior** [comment]
Thank  you for the help Anne. I can run the file now
